services:
  node:
    container_name: nodejs
    image: node:24-alpine
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
